CREATE DATABASE OFICINA_SAEP_DB;
USE OFICINA_SAEP_DB;

CREATE TABLE USUARIOS (
    USU_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(100) NOT NULL,
    USU_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE CLIENTES (
    CLI_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR(100) NOT NULL,
    CLI_CPF VARCHAR(14) NOT NULL UNIQUE,
    CLI_TELEFONE VARCHAR(20) NOT NULL
);

CREATE TABLE VEICULOS (
    VEI_ID INT AUTO_INCREMENT PRIMARY KEY,
    VEI_PLACA VARCHAR(10) NOT NULL UNIQUE,
    VEI_MARCA VARCHAR(50) NOT NULL,
    VEI_MODELO VARCHAR(100) NOT NULL,
    VEI_ANO INT NOT NULL,
    FK_CLI_ID INT NOT NULL,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTES(CLI_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE AGENDAMENTOS (
    AGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    AGE_DATA_HORA DATETIME NOT NULL,
    AGE_SERVICO VARCHAR(150) NOT NULL,
    AGE_STATUS VARCHAR(30) NOT NULL,
    FK_CLI_ID INT NOT NULL,
    FK_VEI_ID INT NOT NULL,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTES(CLI_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (FK_VEI_ID) REFERENCES VEICULOS(VEI_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO USUARIOS (USU_NOME, USU_EMAIL, USU_SENHA) VALUES
('Administrador', 'admin@oficina.com', '123456'),
('Gabriel', 'gabriel@oficina.com', '123456'),
('Luiz', 'luiz@oficina.com', '123456');

INSERT INTO CLIENTES (CLI_NOME, CLI_CPF, CLI_TELEFONE) VALUES
('João da Silva', '111.111.111-11', '(11) 99999-1111'),
('Maria Oliveira', '222.222.222-22', '(11) 99999-2222'),
('Pedro Santos', '333.333.333-33', '(11) 99999-3333');

INSERT INTO VEICULOS (VEI_PLACA, VEI_MARCA, VEI_MODELO, VEI_ANO, FK_CLI_ID) VALUES
('ABC1D23', 'Volkswagen', 'Gol', 2020, 1),
('DEF4G56', 'Chevrolet', 'Onix', 2022, 2),
('GHI7J89', 'Toyota', 'Corolla', 2021, 3);

INSERT INTO AGENDAMENTOS (
    AGE_DATA_HORA,
    AGE_SERVICO,
    AGE_STATUS,
    FK_CLI_ID,
    FK_VEI_ID
) VALUES
('2026-09-10 08:00:00', 'Troca de óleo', 'Agendado', 1, 1),
('2026-09-10 10:00:00', 'Revisão geral', 'Agendado', 2, 2),
('2026-09-11 14:00:00', 'Alinhamento e balanceamento', 'Agendado', 3, 3);